### PR TITLE
build error

### PR DESCRIPTION
**Pull request by rofl0r**
fast-lzma2/radix_bitpack.c:16: error: redefinition of typedef 'FL2_matchTable'
fast-lzma2/radix_mf.h:21: note: previous declaration of 'FL2_matchTable' was here

making a bogus PR because issues are disabled

### CODE REVIEW

**Comment by conor42** [comment]
I've enabled issues. Thanks for pointing that out. The setting was probably inherited from xz.

What OS and compiler are you using? I've only compiled on 64-bit Linux with gcc 7.3 and 8.3, and mingw-w64 with gcc 7.2.

**Comment by rofl0r** [comment]
it's a red hat enterprise linux, with glibc 2.12
`Linux xxxx 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Oct 9 11:31:50 CDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
`gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)`
upstream xz compiles fine

**Comment by conor42** [comment]
In the 'dev' branch I've removed the unnecessary typedefs. It now compiles with gcc 4.7. There are some warnings which later gcc versions don't flag so I'll fix those at some point.

**Comment by rofl0r** [comment]
getting till the linker stage, where i get an error about missing `min`.

see http://ix.io/1G1o for warnings and errors. apparently the header declaring min macro wasnt included properly.

**Comment by conor42** [comment]
The dev branch includes a couple of experimental optimizations I made to the original xz encoder which boost the speed at the cost of slightly worse ratio when using --extreme. This is how the 'min' error crept in. It should be ok now.

**Comment by rofl0r** [comment]
yeah it seems to work now. maybe this issue should be left open till dev is merged into master ? you decide.

**Comment by conor42** [comment]
Soon I'll update master separately without the other changes in dev.
